// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (
    from_user,
    to_user,
    content
) VALUES (
    $1, $2, $3
) RETURNING id, from_user, to_user, content, date_created
`

type CreateMessageParams struct {
	FromUser int64  `json:"from_user"`
	ToUser   int64  `json:"to_user"`
	Content  string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.FromUser, arg.ToUser, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.FromUser,
		&i.ToUser,
		&i.Content,
		&i.DateCreated,
	)
	return i, err
}

const getMessages = `-- name: GetMessages :many
SELECT id, from_user, to_user, content, date_created FROM message 
WHERE (from_user = $1 AND to_user = $2) OR (to_user = $1 AND from_user = $2)
ORDER BY id DESC
`

type GetMessagesParams struct {
	FromUser int64 `json:"from_user"`
	ToUser   int64 `json:"to_user"`
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessages, arg.FromUser, arg.ToUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.FromUser,
			&i.ToUser,
			&i.Content,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
