// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Message struct {
	ID          int64     `json:"id"`
	FromID      int64     `json:"from_id"`
	ToID        int64     `json:"to_id"`
	Content     string    `json:"content"`
	DateCreated time.Time `json:"date_created"`
}

type User struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	UrlAvatar string `json:"url_avatar"`
}
